# Generated by Django 5.1.6 on 2025-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_stock_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_number',
            field=models.CharField(default='QF9UtN', max_length=100),
        ),
    ]
